"""Tracks what `recipe build` last successfully wrote for one recipe, so
`serve` can tell a hand-edit to `compose.yaml`/`Dockerfile` apart from
fllame's own low-risk edits (`config set-default-image`'s text-replace).
Local-machine state only - like the Hugging Face cache itself, it isn't
meant to be portable, backed up, or git-tracked; it's regenerated by the
next successful `recipe build`/`serve` either way.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

import yaml

_FILENAME = ".fllame-build.yaml"


def hash_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


@dataclass(frozen=True)
class BuildState:
    compose_hash: str | None = None
    dockerfile_hash: str | None = None
    # Set when `config set-default-image`'s compose.yaml text-replace
    # touched this recipe but the shared `docker pull` that would
    # confirm the new image actually resolves failed - fllame's own
    # edit, not a hand-edit, so it's a separate, lower-severity flag
    # from the two hashes above rather than another hash mismatch.
    image_synced_via_config: bool = False

    @staticmethod
    def from_dict(data: dict) -> BuildState:
        return BuildState(
            compose_hash=data.get("compose_hash"),
            dockerfile_hash=data.get("dockerfile_hash"),
            image_synced_via_config=bool(data.get("image_synced_via_config", False)),
        )

    def to_dict(self) -> dict:
        data: dict = {}
        if self.compose_hash is not None:
            data["compose_hash"] = self.compose_hash
        if self.dockerfile_hash is not None:
            data["dockerfile_hash"] = self.dockerfile_hash
        if self.image_synced_via_config:
            data["image_synced_via_config"] = True
        return data


def path_for(recipe_dir: Path) -> Path:
    return recipe_dir / _FILENAME


def load(recipe_dir: Path) -> BuildState:
    path = path_for(recipe_dir)
    if not path.is_file():
        return BuildState()
    data = yaml.safe_load(path.read_text()) or {}
    return BuildState.from_dict(data)


def save(recipe_dir: Path, state: BuildState) -> None:
    path_for(recipe_dir).write_text(yaml.safe_dump(state.to_dict(), sort_keys=False))


def for_current_files(recipe_dir: Path, *, image_synced_via_config: bool = False) -> BuildState:
    """The `BuildState` matching `compose.yaml`/`Dockerfile` as they
    stand on disk right now - what gets saved right after a successful
    `recipe build` or `serve`, so neither is later mistaken for having
    drifted since."""
    compose_path = recipe_dir / "compose.yaml"
    dockerfile_path = recipe_dir / "Dockerfile"
    return BuildState(
        compose_hash=hash_text(compose_path.read_text()) if compose_path.is_file() else None,
        dockerfile_hash=(
            hash_text(dockerfile_path.read_text()) if dockerfile_path.is_file() else None
        ),
        image_synced_via_config=image_synced_via_config,
    )
