"""Filesystem locations fllame reads and writes, overridable via env vars."""

from __future__ import annotations

import os
from pathlib import Path

from huggingface_hub import constants as hf_constants


def recipes_dir() -> Path:
    override = os.environ.get("FLLAME_RECIPES_DIR")
    if override:
        return Path(override)
    return Path.home() / ".config" / "fllame" / "recipes"


def state_dir() -> Path:
    override = os.environ.get("FLLAME_STATE_DIR")
    if override:
        return Path(override)
    return Path.home() / ".local" / "state" / "fllame"


def recipe_state_dir(handle: str) -> Path:
    """Where fllame writes HANDLE's self-contained compose folder
    (`docker-compose.yml`, plus a `Dockerfile` when its preinstall step
    needs one) - one folder per recipe, fully owned and regenerated by
    fllame, not hand-edited. Each is independently runnable via plain
    `docker compose up -d` from inside it, with no fllame CLI involved.
    """
    return state_dir() / "recipes" / handle


def compose_project_name(handle: str) -> str:
    """The docker-compose project name for HANDLE's recipe - each
    recipe is its own independent compose project (see
    `recipe_state_dir`), not one project shared across every recipe.
    """
    return f"fllame-{handle}"


def config_file_path() -> Path:
    """A small persisted settings file for cross-invocation CLI defaults
    that aren't per-recipe data (`recipes_dir`) or generated container
    state (`state_dir`) - today just the fallback Docker image (see
    `fllame/config_file.py`, `fllame config`). Read/written directly by
    that module, not hand-edited.
    """
    override = os.environ.get("FLLAME_CONFIG_FILE")
    if override:
        return Path(override)
    return Path.home() / ".config" / "fllame" / "config.yaml"


def hf_cache_dir() -> Path:
    """Wherever huggingface_hub itself resolves its cache to (honoring
    HF_HOME/HF_HUB_CACHE) - fllame deliberately has no opinion of its own
    about where models live on disk.
    """
    return Path(hf_constants.HF_HUB_CACHE)
